"use client";

import { useStore } from "@/lib/store";
import { impact } from "@/lib/impact";
import { agreement } from "@/lib/stats";
import { Badge, PageHeader, StatCard } from "@/components/ui";
import { Callout } from "@/components/Callout";

// Small line chart with an auto-scaled axis
function Line({ values, color, fmt, height = 130 }: { values: number[]; color: string; fmt: (n: number) => string; height?: number }) {
  const w = 520, padL = 44, padB = 20, padT = 10;
  const min = Math.min(...values), max = Math.max(...values);
  const lo = min - (max - min) * 0.15, hi = max + (max - min) * 0.15;
  const x = (i: number) => padL + (i / (values.length - 1)) * (w - padL - 10);
  const y = (v: number) => padT + (1 - (v - lo) / (hi - lo || 1)) * (height - padT - padB);
  const path = values.map((v, i) => `${i ? "L" : "M"}${x(i).toFixed(1)} ${y(v).toFixed(1)}`).join(" ");
  return (
    <svg viewBox={`0 0 ${w} ${height}`} className="w-full">
      {[min, (min + max) / 2, max].map((g, k) => (
        <g key={k}>
          <line x1={padL} x2={w - 10} y1={y(g)} y2={y(g)} stroke="#e9e3ec" />
          <text x={padL - 6} y={y(g) + 4} textAnchor="end" fontSize="10" fill="#6f6475">{fmt(g)}</text>
        </g>
      ))}
      <path d={path} fill="none" stroke={color} strokeWidth={2.6} strokeLinecap="round" strokeLinejoin="round" />
      <circle cx={x(values.length - 1)} cy={y(values[values.length - 1])} r={4} fill={color} />
      <text x={padL} y={height - 4} fontSize="10" fill="#6f6475">12 weeks ago</text>
      <text x={w - 10} y={height - 4} textAnchor="end" fontSize="10" fill="#6f6475">Now</text>
    </svg>
  );
}

export default function Impact() {
  const { data } = useStore();
  const m = impact(data);
  const agree = agreement(data);
  const pct = (a: number, b: number) => Math.round(((b - a) / a) * 100);

  // scatter geometry
  const W = 560, H = 300, pl = 48, pb = 36, pt = 14, pr = 20;
  const xs = m.dots.map((p) => p.x), ys = m.dots.map((p) => p.y);
  const xMin = Math.floor(Math.min(...xs) - 4), xMax = Math.ceil(Math.max(...xs) + 4);
  const yMin = Math.floor(Math.min(...ys) - 1), yMax = Math.ceil(Math.max(...ys) + 1);
  const sx = (v: number) => pl + ((v - xMin) / (xMax - xMin)) * (W - pl - pr);
  const sy = (v: number) => pt + (1 - (v - yMin) / (yMax - yMin)) * (H - pt - pb);

  return (
    <div className="space-y-6">
      <PageHeader
        title="Impact"
        sub="Does practice actually change what guests experience? Seasoned links every practice score to guest complaints, ratings and comp costs."
        right={
          <div className="flex items-center gap-2">
            <Badge tone="gray">Sample outcome data</Badge>
            <Callout align="right" title="Practice linked to outcomes" moat="this history compounds with every shift and can't be generated by prompting an AI.">
              <p>Every practice score is tied to what happens with real guests: complaints, ratings and comp costs.</p>
              <p>That lets a restaurant group see which training actually pays for itself.</p>
            </Callout>
          </div>
        }
      />

      <div className="rounded-2xl border border-cameron-navy/25 bg-cameron-tint/50 px-5 py-4 text-sm text-ink/85">
        <strong className="text-cameron-navy">Why this matters:</strong> anyone can build AI roleplay. What no one else has is a growing record connecting
        <em> practice</em> to <em>real outcomes</em> at every location. A real customer connects their POS and review feeds. This demo models those outcomes from each location&apos;s actual readiness.
      </div>

      <div data-tour="impact-kpis" className="grid gap-4 md:grid-cols-4">
        <StatCard label="Complaints per 1,000 orders" value={m.after.complaints.toFixed(1)} sub={`from ${m.before.complaints.toFixed(1)} 12 weeks ago`} delta={`${pct(m.before.complaints, m.after.complaints)}%`} tone="good" />
        <StatCard label="Average guest rating" value={m.after.rating.toFixed(2)} sub={`from ${m.before.rating.toFixed(2)}`} delta={`+${(m.after.rating - m.before.rating).toFixed(2)}`} tone="good" />
        <StatCard label="Weekly comps & refunds" value={`$${Math.round(m.after.cost).toLocaleString()}`} sub={`down from $${Math.round(m.before.cost).toLocaleString()} · ≈ $${Math.round(m.annualSavings / 1000)}k a year`} tone="good" />
        <StatCard label="AI ↔ manager agreement" value={`${agree.rate}%`} sub={`${agree.total} grades checked by managers`} />
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <div className="card p-6">
          <h2 className="font-display text-xl font-semibold text-plum-800">Readiness went up…</h2>
          <p className="text-xs text-muted">Company-wide average, last 12 weeks</p>
          <div className="mt-3"><Line values={m.readiness} color="#681a43" fmt={(n) => `${Math.round(n)}%`} /></div>
        </div>
        <div className="card p-6">
          <h2 className="font-display text-xl font-semibold text-plum-800">…and complaints came down</h2>
          <p className="text-xs text-muted">Guest complaints per 1,000 orders, same 12 weeks</p>
          <div className="mt-3"><Line values={m.complaints} color="#1c7c54" fmt={(n) => n.toFixed(1)} /></div>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-[1.15fr_1fr]">
        <div className="card p-6">
          <div className="flex flex-wrap items-baseline justify-between gap-2">
            <h2 className="font-display text-xl font-semibold text-plum-800">Better-trained locations get fewer complaints</h2>
            <Badge tone="good">Correlation r = {m.fit.r.toFixed(2)}</Badge>
          </div>
          <p className="text-xs text-muted">Each dot is one location. Left to right: team readiness. Bottom to top: complaints per 1,000 orders.</p>
          <svg viewBox={`0 0 ${W} ${H}`} className="mt-3 w-full">
            {[0, 1, 2, 3].map((k) => {
              const v = yMin + ((yMax - yMin) * k) / 3;
              return (
                <g key={k}>
                  <line x1={pl} x2={W - pr} y1={sy(v)} y2={sy(v)} stroke="#e9e3ec" />
                  <text x={pl - 6} y={sy(v) + 4} textAnchor="end" fontSize="10" fill="#6f6475">{v.toFixed(1)}</text>
                </g>
              );
            })}
            {[0, 1, 2, 3].map((k) => {
              const v = xMin + ((xMax - xMin) * k) / 3;
              return <text key={k} x={sx(v)} y={H - 14} textAnchor="middle" fontSize="10" fill="#6f6475">{Math.round(v)}%</text>;
            })}
            <line x1={sx(xMin)} y1={sy(m.fit.slope * xMin + m.fit.intercept)} x2={sx(xMax)} y2={sy(m.fit.slope * xMax + m.fit.intercept)} stroke="#681a43" strokeDasharray="5 5" strokeOpacity={0.5} />
            {m.dots.map((p, i) => {
              // put the label on the left when a neighbouring dot would sit under it
              const crowded = m.dots.some((q, k) => k < i && Math.abs(sx(q.x) - sx(p.x)) < 70 && Math.abs(sy(q.y) - sy(p.y)) < 16);
              return (
                <g key={p.id}>
                  <circle cx={sx(p.x)} cy={sy(p.y)} r={6} fill="#681a43" fillOpacity={0.85} stroke="#fff" strokeWidth={1.5} />
                  <text x={sx(p.x) + (crowded ? -9 : 9)} y={sy(p.y) + (crowded ? 16 : 4)} textAnchor={crowded ? "end" : "start"} fontSize="10.5" fill="#1e1521">{p.name}</text>
                </g>
              );
            })}
          </svg>
          <p className="mt-2 text-[11px] text-muted">Correlation is not proof. A real pilot would compare trained locations against a control group.</p>
        </div>

        <div className="card p-6">
          <h2 className="font-display text-xl font-semibold text-plum-800">By skill</h2>
          <p className="text-xs text-muted">Average skill score, and guest complaints tied to that skill (per 1,000 orders)</p>
          <div className="mt-4 space-y-4">
            {m.skills.map((s) => (
              <div key={s.cat.id}>
                <div className="flex items-center justify-between text-sm">
                  <span className="font-semibold">{s.cat.name}</span>
                  <Badge tone="good">{Math.round(((s.rateNow - s.rateThen) / s.rateThen) * 100)}% complaints</Badge>
                </div>
                <div className="mt-1 grid grid-cols-2 gap-3 text-xs text-muted">
                  <div>Skill score: {s.scoreThen}% → <strong className="text-ink">{s.scoreNow}%</strong></div>
                  <div>Complaints: {s.rateThen.toFixed(1)} → <strong className="text-ink">{s.rateNow.toFixed(1)}</strong></div>
                </div>
                <div className="mt-1.5 flex h-1.5 overflow-hidden rounded-full bg-plum-100">
                  <div className="h-full bg-plum-700" style={{ width: `${s.scoreNow}%` }} />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
